// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rhtpiygehaYPHyZZdWmjau
// Component: zYKS2FXDESZB
import * as React from "react";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { Avatar } from "inprodi-design-system"; // plasmic-import: LHFWbCJrjoSX/codeComponent
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: rhtpiygehaYPHyZZdWmjau/projectcss
import sty from "./PlasmicUserSelector.module.css"; // plasmic-import: zYKS2FXDESZB/css

createPlasmicElementProxy;

export const PlasmicUserSelector__VariantProps = new Array();

export const PlasmicUserSelector__ArgProps = new Array(
  "value",
  "onValueChange"
);

const $$ = {};

function PlasmicUserSelector__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "value",
        type: "writable",
        variableType: "object",
        valueProp: "value",
        onChangeProp: "onValueChange"
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  return (
    <div
      data-plasmic-name={"mainContainer"}
      data-plasmic-override={overrides.mainContainer}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.mainContainer
      )}
    >
      <Stack__
        as={"div"}
        data-plasmic-name={"userSelector"}
        data-plasmic-override={overrides.userSelector}
        hasGap={true}
        className={classNames(projectcss.all, sty.userSelector)}
        style={(() => {
          try {
            return (() => {
              return {
                boxShadow: $props.value
                  ? "rgba(0, 0, 0, 0.04) 0px 1px 3px 0px, rgba(0, 0, 0, 0.01) 0px 1px 2px 0px"
                  : "none",
                borderStyle: $props.value ? "solid" : "dashed"
              };
            })();
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return undefined;
            }
            throw e;
          }
        })()}
      >
        <Avatar
          data-plasmic-name={"avatar"}
          data-plasmic-override={overrides.avatar}
          bordered={true}
          className={classNames("__wab_instance", sty.avatar)}
          color={(() => {
            try {
              return (() => {
                return $props.value ? "#1f32c4" : "#bfbfbf";
              })();
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return "var(--token-Uo-0jM2UwryY)";
              }
              throw e;
            }
          })()}
          content={(() => {
            try {
              return (() => {
                return $props.value
                  ? $props.value.image?.url
                    ? $props.value.image.url
                    : $props.value.name
                  : "User";
              })();
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()}
          isCircular={true}
          size={"xs"}
          type={(() => {
            try {
              return (() => {
                return $props.value
                  ? $props.value.image?.url
                    ? "image"
                    : "text"
                  : "icon";
              })();
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return "text";
              }
              throw e;
            }
          })()}
          variant={"filled"}
        />

        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text
          )}
          style={(() => {
            try {
              return (() => {
                return { color: $props.value ? "black" : "#868e96" };
              })();
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()}
        >
          <React.Fragment>
            {(() => {
              try {
                return (() => {
                  return $props.value?.name
                    ? $$.parseName($props.value)
                    : "Sin Asignar";
                })();
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
      </Stack__>
    </div>
  );
}

const PlasmicDescendants = {
  mainContainer: ["mainContainer", "userSelector", "avatar", "text"],
  userSelector: ["userSelector", "avatar", "text"],
  avatar: ["avatar"],
  text: ["text"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicUserSelector__ArgProps,
          internalVariantPropNames: PlasmicUserSelector__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicUserSelector__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "mainContainer") {
    func.displayName = "PlasmicUserSelector";
  } else {
    func.displayName = `PlasmicUserSelector.${nodeName}`;
  }
  return func;
}

export const PlasmicUserSelector = Object.assign(
  // Top-level PlasmicUserSelector renders the root element
  makeNodeComponent("mainContainer"),
  {
    // Helper components rendering sub-elements
    userSelector: makeNodeComponent("userSelector"),
    avatar: makeNodeComponent("avatar"),
    text: makeNodeComponent("text"),
    // Metadata about props expected for PlasmicUserSelector
    internalVariantProps: PlasmicUserSelector__VariantProps,
    internalArgProps: PlasmicUserSelector__ArgProps
  }
);

export default PlasmicUserSelector;
/* prettier-ignore-end */
