// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rhtpiygehaYPHyZZdWmjau
// Component: fRC85Ctx5Ezf
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: rhtpiygehaYPHyZZdWmjau/projectcss
import sty from "./PlasmicImageSelector.module.css"; // plasmic-import: fRC85Ctx5Ezf/css

createPlasmicElementProxy;

export const PlasmicImageSelector__VariantProps = new Array();

export const PlasmicImageSelector__ArgProps = new Array(
  "labelAccesor",
  "imageAccesor",
  "emptyLabel",
  "value",
  "onValueChange"
);

const $$ = {};

function PlasmicImageSelector__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          labelAccesor: "name",
          imageAccesor: "image",
          emptyLabel: "Sin Asignar"
        },
        props.args
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "value",
        type: "writable",
        variableType: "object",
        valueProp: "value",
        onChangeProp: "onValueChange"
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  return (
    <div
      data-plasmic-name={"mainContainer"}
      data-plasmic-override={overrides.mainContainer}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.mainContainer
      )}
    >
      <Stack__
        as={"div"}
        data-plasmic-name={"groupSelector"}
        data-plasmic-override={overrides.groupSelector}
        hasGap={true}
        className={classNames(projectcss.all, sty.groupSelector)}
        style={(() => {
          try {
            return (() => {
              return {
                borderStyle: $props.value ? "solid" : "dashed",
                borderColor: $props.value
                  ? "transparent"
                  : "var(--antd-colorBorder)",
                background: $props.value ? "transparent" : "white"
              };
            })();
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return undefined;
            }
            throw e;
          }
        })()}
      >
        {(() => {
          try {
            return (() => {
              return $props.value;
            })();
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return true;
            }
            throw e;
          }
        })() ? (
          <PlasmicImg__
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={"24px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"24px"}
            loading={"lazy"}
            src={(() => {
              try {
                return (() => {
                  return $props.value[$props.imageAccesor];
                })();
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()}
          />
        ) : null}
        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text
          )}
          style={(() => {
            try {
              return (() => {
                return { color: $props.value ? "black" : "#868e96" };
              })();
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()}
        >
          <React.Fragment>
            {(() => {
              try {
                return $props.value
                  ? $props.value[$props.labelAccesor]
                  : $props.emptyLabel;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
      </Stack__>
    </div>
  );
}

const PlasmicDescendants = {
  mainContainer: ["mainContainer", "groupSelector", "img", "text"],
  groupSelector: ["groupSelector", "img", "text"],
  img: ["img"],
  text: ["text"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicImageSelector__ArgProps,
          internalVariantPropNames: PlasmicImageSelector__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicImageSelector__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "mainContainer") {
    func.displayName = "PlasmicImageSelector";
  } else {
    func.displayName = `PlasmicImageSelector.${nodeName}`;
  }
  return func;
}

export const PlasmicImageSelector = Object.assign(
  // Top-level PlasmicImageSelector renders the root element
  makeNodeComponent("mainContainer"),
  {
    // Helper components rendering sub-elements
    groupSelector: makeNodeComponent("groupSelector"),
    img: makeNodeComponent("img"),
    text: makeNodeComponent("text"),
    // Metadata about props expected for PlasmicImageSelector
    internalVariantProps: PlasmicImageSelector__VariantProps,
    internalArgProps: PlasmicImageSelector__ArgProps
  }
);

export default PlasmicImageSelector;
/* prettier-ignore-end */
